// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAciX7byaf2md_IMK5RBR4Rd_AxBTJzPyw',
    appId: '1:837386298671:web:2ec1ff36fb6e781c152dda',
    messagingSenderId: '837386298671',
    projectId: 'kroscek',
    authDomain: 'kroscek.firebaseapp.com',
    databaseURL: 'https://kroscek-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kroscek.appspot.com',
    measurementId: 'G-JJMYBRE23G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNZoDIH3DjLrz77c-ihr0HLhYrgPtfKKc',
    appId: '1:837386298671:android:12e0dd2836875ec3152dda',
    messagingSenderId: '837386298671',
    projectId: 'kroscek',
    databaseURL: 'https://kroscek-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kroscek.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChx7RnMzGaiRiyFUnQ4NlQbVOoDSrIMP4',
    appId: '1:837386298671:ios:86e8c815c2315e3b152dda',
    messagingSenderId: '837386298671',
    projectId: 'kroscek',
    databaseURL: 'https://kroscek-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kroscek.appspot.com',
    androidClientId: '837386298671-d9pnm7dat8iiuqm12hjvakgc4n8btlsf.apps.googleusercontent.com',
    iosClientId: '837386298671-l1hj5okjjh4v954fn9rt3u96e1b3q0i4.apps.googleusercontent.com',
    iosBundleId: 'com.example.kroscek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChx7RnMzGaiRiyFUnQ4NlQbVOoDSrIMP4',
    appId: '1:837386298671:ios:86e8c815c2315e3b152dda',
    messagingSenderId: '837386298671',
    projectId: 'kroscek',
    databaseURL: 'https://kroscek-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kroscek.appspot.com',
    androidClientId: '837386298671-d9pnm7dat8iiuqm12hjvakgc4n8btlsf.apps.googleusercontent.com',
    iosClientId: '837386298671-l1hj5okjjh4v954fn9rt3u96e1b3q0i4.apps.googleusercontent.com',
    iosBundleId: 'com.example.kroscek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAciX7byaf2md_IMK5RBR4Rd_AxBTJzPyw',
    appId: '1:837386298671:web:cfb38a7f5654c74c152dda',
    messagingSenderId: '837386298671',
    projectId: 'kroscek',
    authDomain: 'kroscek.firebaseapp.com',
    databaseURL: 'https://kroscek-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kroscek.appspot.com',
    measurementId: 'G-KV86CS0BN1',
  );
}
