create table if not exists public.audit_pld_lifecycle (
  field_number text not null,
  phase_key text not null check (
    phase_key in (
      'vegetative',
      'generative_1',
      'generative_2',
      'generative_3',
      'generative_4',
      'generative_5',
      'pre_harvest',
      'harvest'
    )
  ),
  status text not null check (status in ('PENDING', 'CONFIRMED', 'UPDATED')),
  recommendation_payload jsonb not null default '{}'::jsonb,
  recommended_flagging text,
  active_flagging text,
  effective_area_ha numeric,
  recommended_at timestamptz not null default now(),
  recommended_by uuid,
  confirmed_at timestamptz,
  confirmed_run_id uuid references public.act_sync_runs(id) on delete set null,
  revised_at timestamptz,
  revised_by uuid,
  updated_at timestamptz not null default now(),
  primary key (field_number, phase_key)
);

create table if not exists public.audit_revision_history (
  id bigint generated by default as identity primary key,
  field_number text not null,
  phase_key text not null,
  audit_table text not null,
  event_type text not null check (
    event_type in (
      'CREATED',
      'UPDATED',
      'BACKFILLED',
      'ACT_CONFIRMED',
      'ACT_REOPENED'
    )
  ),
  old_payload jsonb not null default '{}'::jsonb,
  new_payload jsonb not null default '{}'::jsonb,
  old_flagging text,
  new_flagging text,
  lifecycle_status text check (
    lifecycle_status is null
    or lifecycle_status in ('PENDING', 'CONFIRMED', 'UPDATED')
  ),
  actor_id uuid,
  actor_name text,
  actor_role text,
  act_sync_run_id uuid references public.act_sync_runs(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists audit_pld_lifecycle_status_idx
  on public.audit_pld_lifecycle (status, phase_key, field_number);

create index if not exists audit_revision_history_field_created_idx
  on public.audit_revision_history (field_number, created_at desc);

alter table public.audit_pld_lifecycle enable row level security;
alter table public.audit_revision_history enable row level security;

revoke all on table public.audit_pld_lifecycle from public, anon, authenticated;
revoke all on table public.audit_revision_history from public, anon, authenticated;
grant all on table public.audit_pld_lifecycle to service_role;
grant all on table public.audit_revision_history to service_role;
grant usage, select on sequence public.audit_revision_history_id_seq
  to service_role;

create or replace function public.audit_pld_phase_payload(
  p_table text,
  p_phase text,
  p_row jsonb
)
returns jsonb
language plpgsql
immutable
set search_path = ''
as $$
declare
  v_checkpoint text;
begin
  if p_row is null then return '{}'::jsonb; end if;

  if p_table = 'audit_vegetative' then
    return jsonb_strip_nulls(jsonb_build_object(
      'date', coalesce(p_row -> 'audit_date_user', p_row -> 'date_of_audit', p_row -> 'submitted_at'),
      'decision', coalesce(p_row -> 'decision', p_row -> 'final_decision'),
      'action_needed', p_row -> 'action_needed',
      'flagging', coalesce(p_row -> 'flagging', p_row -> 'final_flagging'),
      'pld_reason', p_row -> 'pld_reason',
      'remarks', p_row -> 'remarks'
    ));
  end if;

  if p_table = 'audit_generative' then
    v_checkpoint := split_part(p_phase, '_', 2);
    return jsonb_strip_nulls(jsonb_build_object(
      'date', coalesce(
        p_row -> ('date_of_audit_' || v_checkpoint),
        p_row -> ('submitted_at_' || v_checkpoint)
      ),
      'decision', p_row -> ('final_decision_' || v_checkpoint),
      'action_needed', p_row -> ('action_needed_' || v_checkpoint),
      'flagging', coalesce(
        p_row -> ('final_flagging_' || v_checkpoint),
        p_row -> ('flagging_' || v_checkpoint),
        case when v_checkpoint = '3' then p_row -> 'flagging' end
      ),
      'remarks', coalesce(
        p_row -> ('remarks_' || v_checkpoint),
        p_row -> ('remark_' || v_checkpoint)
      )
    ));
  end if;

  if p_table = 'audit_pre_harvest' then
    return jsonb_strip_nulls(jsonb_build_object(
      'date', coalesce(p_row -> 'audit_date', p_row -> 'date_of_audit', p_row -> 'submitted_at'),
      'decision', coalesce(p_row -> 'final_decision', p_row -> 'decision'),
      'action_needed', p_row -> 'action_needed',
      'flagging', coalesce(p_row -> 'final_flagging', p_row -> 'flagging'),
      'discard_area', coalesce(p_row -> 'discard_area', p_row -> 'discard_area_ha'),
      'discard_reason', p_row -> 'discard_reason',
      'remarks', p_row -> 'remarks'
    ));
  end if;

  if p_table = 'audit_harvest' then
    return jsonb_strip_nulls(jsonb_build_object(
      'date', coalesce(p_row -> 'date_of_audit', p_row -> 'audit_date', p_row -> 'submitted_at'),
      'decision', coalesce(p_row -> 'final_decision', p_row -> 'status_downgrade'),
      'action_needed', p_row -> 'action_needed',
      'flagging', coalesce(
        p_row -> 'final_flagging',
        p_row -> 'downgrade_flagging',
        p_row -> 'flagging'
      ),
      'remarks', p_row -> 'remarks'
    ));
  end if;

  return '{}'::jsonb;
end;
$$;

revoke all on function public.audit_pld_phase_payload(text, text, jsonb)
  from public, anon, authenticated;
grant execute on function public.audit_pld_phase_payload(text, text, jsonb)
  to service_role;

create or replace function public.audit_pld_payload_is_terminal(p_payload jsonb)
returns boolean
language plpgsql
immutable
set search_path = ''
as $$
declare
  v_key text;
  v_value text;
begin
  for v_key, v_value in
    select entry.key, upper(btrim(entry.value #>> '{}'))
    from jsonb_each(coalesce(p_payload, '{}'::jsonb)) entry
    where entry.key in ('decision', 'action_needed', 'flagging')
  loop
    if v_value = '' or v_value like '%PARTIAL%' then continue; end if;
    if v_value like '%PLD%' or v_value like '%DISCARD%' then return true; end if;
    if v_key = 'decision' and v_value = 'D' then return true; end if;
    if v_key = 'action_needed' and v_value in ('F', 'G') then return true; end if;
  end loop;
  return false;
end;
$$;

create or replace function public.audit_pld_payload_active_flag(p_payload jsonb)
returns text
language sql
immutable
set search_path = ''
as $$
  select case
    when upper(btrim(coalesce(p_payload ->> 'flagging', ''))) in ('GF', 'RFI', 'RFD')
      then upper(btrim(p_payload ->> 'flagging'))
    else null
  end;
$$;

create or replace function public.audit_pld_payload_primary_value(p_payload jsonb)
returns text
language sql
immutable
set search_path = ''
as $$
  select nullif(btrim(coalesce(
    p_payload ->> 'flagging',
    p_payload ->> 'decision',
    p_payload ->> 'action_needed'
  )), '');
$$;

revoke all on function public.audit_pld_payload_is_terminal(jsonb)
  from public, anon, authenticated;
revoke all on function public.audit_pld_payload_active_flag(jsonb)
  from public, anon, authenticated;
revoke all on function public.audit_pld_payload_primary_value(jsonb)
  from public, anon, authenticated;
grant execute on function public.audit_pld_payload_is_terminal(jsonb)
  to service_role;
grant execute on function public.audit_pld_payload_active_flag(jsonb)
  to service_role;
grant execute on function public.audit_pld_payload_primary_value(jsonb)
  to service_role;

create or replace function public.audit_pld_phase_keys(p_table text)
returns text[]
language sql
immutable
set search_path = ''
as $$
  select case p_table
    when 'audit_vegetative' then array['vegetative']::text[]
    when 'audit_generative' then array[
      'generative_1', 'generative_2', 'generative_3',
      'generative_4', 'generative_5'
    ]::text[]
    when 'audit_pre_harvest' then array['pre_harvest']::text[]
    when 'audit_harvest' then array['harvest']::text[]
    else '{}'::text[]
  end;
$$;

revoke all on function public.audit_pld_phase_keys(text)
  from public, anon, authenticated;
grant execute on function public.audit_pld_phase_keys(text) to service_role;

create or replace function public.guard_confirmed_act_pld_audit()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_phase text;
  v_field_number text := coalesce(new.field_number, old.field_number);
begin
  if current_setting('app.audit_pld_bypass', true) = 'on' then
    if tg_op = 'DELETE' then return old; end if;
    return new;
  end if;

  foreach v_phase in array public.audit_pld_phase_keys(tg_table_name) loop
    if public.audit_pld_phase_payload(tg_table_name, v_phase, to_jsonb(old))
       is distinct from
       public.audit_pld_phase_payload(tg_table_name, v_phase, to_jsonb(new))
       and exists (
         select 1
         from public.audit_pld_lifecycle lifecycle
         where upper(regexp_replace(btrim(lifecycle.field_number), '[[:space:]]+', '', 'g')) =
           upper(regexp_replace(btrim(v_field_number), '[[:space:]]+', '', 'g'))
           and lifecycle.phase_key = v_phase
           and lifecycle.status = 'CONFIRMED'
       ) then
      raise exception using
        errcode = 'P0001',
        message = format(
          'PLD_ACT_CONFIRMED_LOCKED:%s:%s',
          v_field_number,
          v_phase
        );
    end if;
  end loop;

  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

revoke all on function public.guard_confirmed_act_pld_audit()
  from public, anon, authenticated;
grant execute on function public.guard_confirmed_act_pld_audit()
  to service_role;

create or replace function public.track_audit_pld_revision()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_phase text;
  v_field_number text := new.field_number;
  v_canonical_field_number text;
  v_old_payload jsonb;
  v_new_payload jsonb;
  v_old_terminal boolean;
  v_new_terminal boolean;
  v_active_flag text;
  v_primary_value text;
  v_effective numeric;
  v_status text;
  v_actor_name text;
  v_actor_role text;
begin
  select mf.field_number, mf.effective_area_ha
  into v_canonical_field_number, v_effective
  from public.master_fields mf
  where upper(regexp_replace(btrim(mf.field_number), '[[:space:]]+', '', 'g')) =
    upper(regexp_replace(btrim(v_field_number), '[[:space:]]+', '', 'g'))
  order by mf.field_number
  limit 1;

  v_field_number := coalesce(v_canonical_field_number, v_field_number);

  select u.name, upper(btrim(u.role))
  into v_actor_name, v_actor_role
  from public.app_users u
  where u.id = auth.uid()
  limit 1;

  foreach v_phase in array public.audit_pld_phase_keys(tg_table_name) loop
    v_old_payload := case when tg_op = 'INSERT' then '{}'::jsonb
      else public.audit_pld_phase_payload(tg_table_name, v_phase, to_jsonb(old)) end;
    v_new_payload := public.audit_pld_phase_payload(
      tg_table_name,
      v_phase,
      to_jsonb(new)
    );

    if v_old_payload is not distinct from v_new_payload then continue; end if;

    v_old_terminal := public.audit_pld_payload_is_terminal(v_old_payload);
    v_new_terminal := public.audit_pld_payload_is_terminal(v_new_payload);
    v_active_flag := public.audit_pld_payload_active_flag(v_new_payload);
    v_primary_value := public.audit_pld_payload_primary_value(v_new_payload);
    v_status := null;

    if v_new_terminal then
      v_status := case when v_effective is not null and v_effective <= 0
        then 'CONFIRMED' else 'PENDING' end;

      insert into public.audit_pld_lifecycle (
        field_number,
        phase_key,
        status,
        recommendation_payload,
        recommended_flagging,
        active_flagging,
        effective_area_ha,
        recommended_at,
        recommended_by,
        confirmed_at,
        confirmed_run_id,
        revised_at,
        revised_by,
        updated_at
      ) values (
        v_field_number,
        v_phase,
        v_status,
        v_new_payload,
        v_primary_value,
        null,
        v_effective,
        now(),
        auth.uid(),
        case when v_status = 'CONFIRMED' then now() end,
        case when v_status = 'CONFIRMED' then (
          select r.id
          from public.act_sync_runs r
          where r.dry_run = false and r.status = 'COMPLETED'
          order by r.completed_at desc nulls last, r.started_at desc
          limit 1
        ) end,
        null,
        null,
        now()
      )
      on conflict (field_number, phase_key) do update set
        status = excluded.status,
        recommendation_payload = excluded.recommendation_payload,
        recommended_flagging = excluded.recommended_flagging,
        active_flagging = null,
        effective_area_ha = excluded.effective_area_ha,
        recommended_at = case
          when public.audit_pld_lifecycle.status = 'UPDATED'
            then excluded.recommended_at
          else public.audit_pld_lifecycle.recommended_at
        end,
        recommended_by = case
          when public.audit_pld_lifecycle.status = 'UPDATED'
            then excluded.recommended_by
          else public.audit_pld_lifecycle.recommended_by
        end,
        confirmed_at = excluded.confirmed_at,
        confirmed_run_id = excluded.confirmed_run_id,
        revised_at = null,
        revised_by = null,
        updated_at = now();
    elsif v_old_terminal and v_active_flag is not null and v_effective > 0 then
      v_status := 'UPDATED';
      update public.audit_pld_lifecycle
      set status = 'UPDATED',
          active_flagging = v_active_flag,
          effective_area_ha = v_effective,
          revised_at = now(),
          revised_by = auth.uid(),
          updated_at = now()
      where field_number = v_field_number
        and phase_key = v_phase;
    else
      select lifecycle.status
      into v_status
      from public.audit_pld_lifecycle lifecycle
      where lifecycle.field_number = v_field_number
        and lifecycle.phase_key = v_phase;
    end if;

    insert into public.audit_revision_history (
      field_number,
      phase_key,
      audit_table,
      event_type,
      old_payload,
      new_payload,
      old_flagging,
      new_flagging,
      lifecycle_status,
      actor_id,
      actor_name,
      actor_role
    ) values (
      v_field_number,
      v_phase,
      tg_table_name,
      case when tg_op = 'INSERT' then 'CREATED' else 'UPDATED' end,
      v_old_payload,
      v_new_payload,
      public.audit_pld_payload_primary_value(v_old_payload),
      v_primary_value,
      v_status,
      auth.uid(),
      v_actor_name,
      v_actor_role
    );
  end loop;

  return new;
end;
$$;

revoke all on function public.track_audit_pld_revision()
  from public, anon, authenticated;
grant execute on function public.track_audit_pld_revision()
  to service_role;

do $$
declare
  v_table text;
begin
  foreach v_table in array array[
    'audit_vegetative',
    'audit_generative',
    'audit_pre_harvest',
    'audit_harvest'
  ] loop
    execute format(
      'drop trigger if exists %I on public.%I',
      'guard_confirmed_act_pld_' || v_table,
      v_table
    );
    execute format(
      'create trigger %I before update or delete on public.%I for each row execute function public.guard_confirmed_act_pld_audit()',
      'guard_confirmed_act_pld_' || v_table,
      v_table
    );
    execute format(
      'drop trigger if exists %I on public.%I',
      'track_audit_pld_revision_' || v_table,
      v_table
    );
    execute format(
      'create trigger %I after insert or update on public.%I for each row execute function public.track_audit_pld_revision()',
      'track_audit_pld_revision_' || v_table,
      v_table
    );
  end loop;
end;
$$;

create or replace function public.refresh_audit_pld_lifecycle_for_field(
  p_field_number text,
  p_run_id uuid default null
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_effective numeric;
  v_item record;
  v_payload jsonb;
  v_active_flag text;
  v_new_status text;
  v_changed integer := 0;
begin
  select mf.effective_area_ha
  into v_effective
  from public.master_fields mf
  where upper(regexp_replace(btrim(mf.field_number), '[[:space:]]+', '', 'g')) =
    upper(regexp_replace(btrim(p_field_number), '[[:space:]]+', '', 'g'))
  order by mf.field_number
  limit 1;

  for v_item in
    select lifecycle.*
    from public.audit_pld_lifecycle lifecycle
    where upper(regexp_replace(btrim(lifecycle.field_number), '[[:space:]]+', '', 'g')) =
      upper(regexp_replace(btrim(p_field_number), '[[:space:]]+', '', 'g'))
  loop
    if v_item.phase_key = 'vegetative' then
      select public.audit_pld_phase_payload(
        'audit_vegetative', v_item.phase_key, to_jsonb(audit)
      ) into v_payload
      from public.audit_vegetative audit
      where upper(regexp_replace(btrim(audit.field_number), '[[:space:]]+', '', 'g')) =
        upper(regexp_replace(btrim(p_field_number), '[[:space:]]+', '', 'g'))
      limit 1;
    elsif v_item.phase_key like 'generative_%' then
      select public.audit_pld_phase_payload(
        'audit_generative', v_item.phase_key, to_jsonb(audit)
      ) into v_payload
      from public.audit_generative audit
      where upper(regexp_replace(btrim(audit.field_number), '[[:space:]]+', '', 'g')) =
        upper(regexp_replace(btrim(p_field_number), '[[:space:]]+', '', 'g'))
      limit 1;
    elsif v_item.phase_key = 'pre_harvest' then
      select public.audit_pld_phase_payload(
        'audit_pre_harvest', v_item.phase_key, to_jsonb(audit)
      ) into v_payload
      from public.audit_pre_harvest audit
      where upper(regexp_replace(btrim(audit.field_number), '[[:space:]]+', '', 'g')) =
        upper(regexp_replace(btrim(p_field_number), '[[:space:]]+', '', 'g'))
      limit 1;
    else
      select public.audit_pld_phase_payload(
        'audit_harvest', v_item.phase_key, to_jsonb(audit)
      ) into v_payload
      from public.audit_harvest audit
      where upper(regexp_replace(btrim(audit.field_number), '[[:space:]]+', '', 'g')) =
        upper(regexp_replace(btrim(p_field_number), '[[:space:]]+', '', 'g'))
      limit 1;
    end if;

    v_payload := coalesce(v_payload, '{}'::jsonb);
    v_active_flag := public.audit_pld_payload_active_flag(v_payload);

    if public.audit_pld_payload_is_terminal(v_payload) then
      v_new_status := case when v_effective is not null and v_effective <= 0
        then 'CONFIRMED' else 'PENDING' end;
    elsif v_active_flag is not null and v_effective > 0 then
      v_new_status := 'UPDATED';
    else
      continue;
    end if;

    if v_item.status is distinct from v_new_status
       or v_item.effective_area_ha is distinct from v_effective then
      update public.audit_pld_lifecycle
      set status = v_new_status,
          active_flagging = case when v_new_status = 'UPDATED'
            then v_active_flag else null end,
          effective_area_ha = v_effective,
          confirmed_at = case when v_new_status = 'CONFIRMED'
            then now() else null end,
          confirmed_run_id = case when v_new_status = 'CONFIRMED'
            then p_run_id else null end,
          updated_at = now()
      where upper(regexp_replace(btrim(field_number), '[[:space:]]+', '', 'g')) =
        upper(regexp_replace(btrim(p_field_number), '[[:space:]]+', '', 'g'))
        and phase_key = v_item.phase_key;

      insert into public.audit_revision_history (
        field_number,
        phase_key,
        audit_table,
        event_type,
        old_payload,
        new_payload,
        old_flagging,
        new_flagging,
        lifecycle_status,
        act_sync_run_id
      ) values (
        p_field_number,
        v_item.phase_key,
        case
          when v_item.phase_key = 'vegetative' then 'audit_vegetative'
          when v_item.phase_key like 'generative_%' then 'audit_generative'
          when v_item.phase_key = 'pre_harvest' then 'audit_pre_harvest'
          else 'audit_harvest'
        end,
        case when v_new_status = 'CONFIRMED'
          then 'ACT_CONFIRMED' else 'ACT_REOPENED' end,
        v_item.recommendation_payload,
        v_payload,
        v_item.recommended_flagging,
        public.audit_pld_payload_primary_value(v_payload),
        v_new_status,
        p_run_id
      );
      v_changed := v_changed + 1;
    end if;
  end loop;

  return v_changed;
end;
$$;

revoke all on function public.refresh_audit_pld_lifecycle_for_field(text, uuid)
  from public, anon, authenticated;
grant execute on function public.refresh_audit_pld_lifecycle_for_field(text, uuid)
  to service_role;

create or replace function public.refresh_audit_pld_after_act_field_update()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_run_id uuid;
begin
  if old.effective_area_ha is not distinct from new.effective_area_ha then
    return new;
  end if;

  select run.id
  into v_run_id
  from public.act_sync_changes change
  join public.act_sync_runs run on run.id = change.run_id
  where change.field_number_norm = upper(
      regexp_replace(btrim(new.field_number), '[[:space:]]+', '', 'g')
    )
    and change.changed_columns ? 'effective_area_ha'
    and run.dry_run = false
    and run.status in ('APPLYING', 'COMPLETED')
  order by run.started_at desc
  limit 1;

  if v_run_id is not null then
    perform public.refresh_audit_pld_lifecycle_for_field(
      new.field_number,
      v_run_id
    );
  end if;

  return new;
end;
$$;

revoke all on function public.refresh_audit_pld_after_act_field_update()
  from public, anon, authenticated;
grant execute on function public.refresh_audit_pld_after_act_field_update()
  to service_role;

drop trigger if exists refresh_audit_pld_after_act_field_update
  on public.master_fields;
create trigger refresh_audit_pld_after_act_field_update
after update of effective_area_ha on public.master_fields
for each row execute function public.refresh_audit_pld_after_act_field_update();

with latest_run as (
  select run.id, run.completed_at
  from public.act_sync_runs run
  where run.dry_run = false and run.status = 'COMPLETED'
  order by run.completed_at desc nulls last, run.started_at desc
  limit 1
),
audit_phases as (
  select
    audit.field_number,
    'vegetative'::text as phase_key,
    'audit_vegetative'::text as audit_table,
    public.audit_pld_phase_payload(
      'audit_vegetative', 'vegetative', to_jsonb(audit)
    ) as payload
  from public.audit_vegetative audit

  union all

  select
    audit.field_number,
    phase.phase_key,
    'audit_generative',
    public.audit_pld_phase_payload(
      'audit_generative', phase.phase_key, to_jsonb(audit)
    )
  from public.audit_generative audit
  cross join unnest(array[
    'generative_1', 'generative_2', 'generative_3',
    'generative_4', 'generative_5'
  ]) phase(phase_key)

  union all

  select
    audit.field_number,
    'pre_harvest',
    'audit_pre_harvest',
    public.audit_pld_phase_payload(
      'audit_pre_harvest', 'pre_harvest', to_jsonb(audit)
    )
  from public.audit_pre_harvest audit

  union all

  select
    audit.field_number,
    'harvest',
    'audit_harvest',
    public.audit_pld_phase_payload(
      'audit_harvest', 'harvest', to_jsonb(audit)
    )
  from public.audit_harvest audit
),
terminal as (
  select
    phase.*,
    mf.field_number as canonical_field_number,
    mf.effective_area_ha,
    run.id as run_id,
    run.completed_at
  from audit_phases phase
  join public.master_fields mf
    on upper(regexp_replace(btrim(mf.field_number), '[[:space:]]+', '', 'g')) =
      upper(regexp_replace(btrim(phase.field_number), '[[:space:]]+', '', 'g'))
  left join latest_run run on true
  where public.audit_pld_payload_is_terminal(phase.payload)
)
insert into public.audit_pld_lifecycle (
  field_number,
  phase_key,
  status,
  recommendation_payload,
  recommended_flagging,
  effective_area_ha,
  recommended_at,
  confirmed_at,
  confirmed_run_id,
  updated_at
)
select
  terminal.canonical_field_number,
  terminal.phase_key,
  case when terminal.effective_area_ha is not null
      and terminal.effective_area_ha <= 0
    then 'CONFIRMED' else 'PENDING' end,
  terminal.payload,
  public.audit_pld_payload_primary_value(terminal.payload),
  terminal.effective_area_ha,
  now(),
  case when terminal.effective_area_ha is not null
      and terminal.effective_area_ha <= 0
    then coalesce(terminal.completed_at, now()) end,
  case when terminal.effective_area_ha is not null
      and terminal.effective_area_ha <= 0
    then terminal.run_id end,
  now()
from terminal
on conflict (field_number, phase_key) do nothing;

insert into public.audit_revision_history (
  field_number,
  phase_key,
  audit_table,
  event_type,
  new_payload,
  new_flagging,
  lifecycle_status,
  act_sync_run_id,
  created_at
)
select
  lifecycle.field_number,
  lifecycle.phase_key,
  case
    when lifecycle.phase_key = 'vegetative' then 'audit_vegetative'
    when lifecycle.phase_key like 'generative_%' then 'audit_generative'
    when lifecycle.phase_key = 'pre_harvest' then 'audit_pre_harvest'
    else 'audit_harvest'
  end,
  'BACKFILLED',
  lifecycle.recommendation_payload,
  lifecycle.recommended_flagging,
  lifecycle.status,
  lifecycle.confirmed_run_id,
  lifecycle.recommended_at
from public.audit_pld_lifecycle lifecycle
where not exists (
  select 1
  from public.audit_revision_history history
  where history.field_number = lifecycle.field_number
    and history.phase_key = lifecycle.phase_key
);

create or replace function public.get_field_pld_audit_lifecycle(
  p_field_number text
)
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  with viewer_scope as (
    select
      upper(btrim(users.role)) as role,
      btrim(users.name) as name,
      upper(btrim(users.role)) in ('ADMIN', 'DEV', 'MANAGER') as can_view_all
    from public.app_users users
    where users.id = auth.uid()
      and coalesce(users.is_active, true) = true

    union all

    select 'SERVICE_ROLE', '', true
    where auth.role() = 'service_role'
  ),
  field as (
    select mf.*
    from public.master_fields mf
    where upper(regexp_replace(btrim(mf.field_number), '[[:space:]]+', '', 'g')) =
      upper(regexp_replace(btrim(p_field_number), '[[:space:]]+', '', 'g'))
    order by mf.field_number
    limit 1
  ),
  allowed as (
    select field.field_number
    from field
    where exists (
      select 1
      from viewer_scope scope
      where scope.can_view_all
        or (
          scope.role = 'SPV'
          and public.act_monitor_name_matches(field.qa_spv, scope.name)
        )
        or (
          scope.role = 'FI'
          and public.act_monitor_name_matches(field.qa_fi, scope.name)
        )
    )
  )
  select jsonb_build_object(
    'field_number', (select field_number from allowed),
    'viewer_role', coalesce((select role from viewer_scope limit 1), 'NONE'),
    'can_revise', coalesce((
      select role in ('ADMIN', 'DEV', 'MANAGER', 'FI', 'SERVICE_ROLE')
      from viewer_scope
      limit 1
    ), false),
    'statuses', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'phase_key', lifecycle.phase_key,
          'status', lifecycle.status,
          'recommended_flagging', lifecycle.recommended_flagging,
          'active_flagging', lifecycle.active_flagging,
          'effective_area_ha', lifecycle.effective_area_ha,
          'recommended_at', lifecycle.recommended_at,
          'confirmed_at', lifecycle.confirmed_at,
          'confirmed_run_id', lifecycle.confirmed_run_id,
          'revised_at', lifecycle.revised_at,
          'updated_at', lifecycle.updated_at,
          'locked', lifecycle.status = 'CONFIRMED'
        )
        order by case lifecycle.phase_key
          when 'vegetative' then 1
          when 'generative_1' then 2
          when 'generative_2' then 3
          when 'generative_3' then 4
          when 'generative_4' then 5
          when 'generative_5' then 6
          when 'pre_harvest' then 7
          else 8
        end
      )
      from public.audit_pld_lifecycle lifecycle
      join allowed on upper(regexp_replace(btrim(allowed.field_number), '[[:space:]]+', '', 'g')) =
        upper(regexp_replace(btrim(lifecycle.field_number), '[[:space:]]+', '', 'g'))
    ), '[]'::jsonb),
    'history', coalesce((
      select jsonb_agg(to_jsonb(item) order by item.created_at desc)
      from (
        select
          history.id,
          history.phase_key,
          history.event_type,
          history.old_payload,
          history.new_payload,
          history.old_flagging,
          history.new_flagging,
          history.lifecycle_status,
          history.actor_name,
          history.actor_role,
          history.act_sync_run_id,
          history.created_at
        from public.audit_revision_history history
        join allowed on upper(regexp_replace(btrim(allowed.field_number), '[[:space:]]+', '', 'g')) =
          upper(regexp_replace(btrim(history.field_number), '[[:space:]]+', '', 'g'))
        order by history.created_at desc
        limit 100
      ) item
    ), '[]'::jsonb)
  );
$$;

revoke all on function public.get_field_pld_audit_lifecycle(text)
  from public, anon;
grant execute on function public.get_field_pld_audit_lifecycle(text)
  to authenticated, service_role;

comment on table public.audit_pld_lifecycle is
  'Current per-phase KC PLD recommendation state: Pending ACT, Confirmed by ACT, or Updated back to an active QA flag.';
comment on table public.audit_revision_history is
  'Append-only per-phase audit revision trail, including ACT confirmation transitions.';
comment on function public.get_field_pld_audit_lifecycle(text) is
  'Returns role-scoped per-phase PLD status and revision history for a Field Number.';
