create table if not exists public.act_sync_runs (
  id uuid primary key default gen_random_uuid(),
  status text not null default 'EXTRACTING'
    check (status in ('EXTRACTING', 'WAITING_EXPORT', 'VALIDATING', 'READY', 'APPLYING', 'COMPLETED', 'BLOCKED', 'FAILED')),
  dry_run boolean not null default true,
  source_from date not null,
  source_to date not null,
  requested_sources text[] not null default array['FC', 'PS', 'SC']::text[],
  requested_by uuid,
  source_counts jsonb not null default '{}'::jsonb,
  source_meta jsonb not null default '{}'::jsonb,
  summary jsonb not null default '{}'::jsonb,
  error_message text,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint act_sync_runs_date_order check (source_from <= source_to)
);

create table if not exists public.act_sync_rows (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.act_sync_runs(id) on delete cascade,
  source_type text not null check (source_type in ('FC', 'PS', 'SC')),
  source_row integer not null,
  field_number_raw text,
  field_number_norm text,
  raw_payload jsonb not null default '{}'::jsonb,
  source_payload jsonb not null default '{}'::jsonb,
  row_hash text not null,
  validation_errors text[] not null default '{}'::text[],
  created_at timestamptz not null default now(),
  unique (run_id, source_type, source_row)
);

create table if not exists public.act_sync_changes (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.act_sync_runs(id) on delete cascade,
  field_number_norm text not null,
  source_type text check (source_type in ('FC', 'PS', 'SC')),
  change_kind text not null check (
    change_kind in (
      'INSERT',
      'UPDATE',
      'UNCHANGED',
      'INVALID',
      'CONFLICT_SOURCE_DUPLICATE',
      'CONFLICT_KC_DUPLICATE',
      'MISSING_SOURCE'
    )
  ),
  current_payload jsonb,
  source_payload jsonb,
  changed_columns jsonb not null default '{}'::jsonb,
  validation_errors text[] not null default '{}'::text[],
  applied boolean not null default false,
  applied_at timestamptz,
  apply_error text,
  created_at timestamptz not null default now(),
  unique (run_id, field_number_norm)
);

create table if not exists public.act_master_fields_change_log (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.act_sync_runs(id) on delete restrict,
  field_number text not null,
  operation text not null check (operation in ('INSERT', 'UPDATE')),
  source_type text not null check (source_type in ('FC', 'PS', 'SC')),
  changed_columns jsonb not null default '{}'::jsonb,
  before_payload jsonb,
  after_payload jsonb not null,
  applied_at timestamptz not null default now()
);

create index if not exists act_sync_runs_started_idx
  on public.act_sync_runs (started_at desc);

create index if not exists act_sync_rows_run_field_idx
  on public.act_sync_rows (run_id, field_number_norm);

create index if not exists act_sync_changes_run_kind_idx
  on public.act_sync_changes (run_id, change_kind);

create index if not exists act_master_fields_change_log_field_idx
  on public.act_master_fields_change_log (field_number, applied_at desc);

alter table public.act_sync_runs enable row level security;
alter table public.act_sync_rows enable row level security;
alter table public.act_sync_changes enable row level security;
alter table public.act_master_fields_change_log enable row level security;

revoke all on table public.act_sync_runs from anon, authenticated;
revoke all on table public.act_sync_rows from anon, authenticated;
revoke all on table public.act_sync_changes from anon, authenticated;
revoke all on table public.act_master_fields_change_log from anon, authenticated;

grant all on table public.act_sync_runs to service_role;
grant all on table public.act_sync_rows to service_role;
grant all on table public.act_sync_changes to service_role;
grant all on table public.act_master_fields_change_log to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.act_master_fields_sync_snapshot(
  p_row public.master_fields
)
returns jsonb
language sql
stable
set search_path = public
as $$
  select jsonb_build_object(
    'field_number', p_row.field_number,
    'farmer_name', p_row.farmer_name,
    'grower', p_row.grower,
    'hybrid', p_row.hybrid,
    'total_area_planted_ha', p_row.total_area_planted_ha,
    'discard_area_ha', p_row.discard_area_ha,
    'effective_area_ha', p_row.effective_area_ha,
    'planting_date_pdn', p_row.planting_date_pdn,
    'hamlet_dusun', p_row.hamlet_dusun,
    'village_desa', p_row.village_desa,
    'sub_district_kec', p_row.sub_district_kec,
    'district_kab', p_row.district_kab,
    'fa', p_row.fa,
    'field_spv', p_row.field_spv,
    'coordinate', p_row.coordinate,
    'region', p_row.region,
    'area_manager', p_row.area_manager,
    'type', p_row.type,
    'prov', p_row.prov,
    'planting_ratio', p_row.planting_ratio,
    'planting_space', p_row.planting_space,
    'geometry_wkt', p_row.geometry_wkt,
    'geometry_source', p_row.geometry_source,
    'is_active', p_row.is_active
  );
$$;

revoke all on function public.act_master_fields_sync_snapshot(public.master_fields)
  from public, anon, authenticated;
grant execute on function public.act_master_fields_sync_snapshot(public.master_fields)
  to service_role;

create or replace function public.apply_act_master_fields_sync(
  p_run_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_run public.act_sync_runs%rowtype;
  v_change public.act_sync_changes%rowtype;
  v_before public.master_fields%rowtype;
  v_after public.master_fields%rowtype;
  v_patch jsonb;
  v_match_count integer;
  v_inserted integer := 0;
  v_updated integer := 0;
begin
  select *
  into v_run
  from public.act_sync_runs
  where id = p_run_id
  for update;

  if not found then
    raise exception 'ACT sync run not found: %', p_run_id;
  end if;
  if v_run.dry_run then
    raise exception 'Dry-run cannot be applied: %', p_run_id;
  end if;
  if v_run.status <> 'READY' then
    raise exception 'ACT sync run must be READY, current status: %', v_run.status;
  end if;
  if exists (
    select 1
    from public.act_sync_changes
    where run_id = p_run_id
      and change_kind in ('INVALID', 'CONFLICT_SOURCE_DUPLICATE', 'CONFLICT_KC_DUPLICATE')
  ) then
    raise exception 'ACT sync run contains blocking validation errors: %', p_run_id;
  end if;

  update public.act_sync_runs
  set status = 'APPLYING'
  where id = p_run_id;

  for v_change in
    select *
    from public.act_sync_changes
    where run_id = p_run_id
      and change_kind in ('INSERT', 'UPDATE')
      and applied = false
    order by id
  loop
    select count(*)
    into v_match_count
    from public.master_fields mf
    where upper(btrim(mf.field_number)) = v_change.field_number_norm;

    if v_match_count > 1 then
      raise exception 'Duplicate normalized field_number in KC during apply: %',
        v_change.field_number_norm;
    end if;

    if v_change.change_kind = 'UPDATE' then
      if v_match_count = 0 then
        raise exception 'KC field disappeared before apply: %', v_change.field_number_norm;
      end if;

      select mf.*
      into v_before
      from public.master_fields mf
      where upper(btrim(mf.field_number)) = v_change.field_number_norm
      for update;

      v_patch := v_change.source_payload - 'field_number';
      if lower(coalesce(v_before.geometry_source, '')) in ('manual', 'kc_manual') then
        v_patch := v_patch - 'geometry_wkt';
      end if;

      select *
      into v_after
      from jsonb_populate_record(v_before, v_patch);

      update public.master_fields
      set farmer_name = v_after.farmer_name,
          grower = v_after.grower,
          hybrid = v_after.hybrid,
          total_area_planted_ha = v_after.total_area_planted_ha,
          discard_area_ha = v_after.discard_area_ha,
          effective_area_ha = v_after.effective_area_ha,
          planting_date_pdn = v_after.planting_date_pdn,
          hamlet_dusun = v_after.hamlet_dusun,
          village_desa = v_after.village_desa,
          sub_district_kec = v_after.sub_district_kec,
          district_kab = v_after.district_kab,
          fa = v_after.fa,
          field_spv = v_after.field_spv,
          coordinate = v_after.coordinate,
          region = v_after.region,
          area_manager = v_after.area_manager,
          type = v_after.type,
          prov = v_after.prov,
          planting_ratio = v_after.planting_ratio,
          planting_space = v_after.planting_space,
          geometry_wkt = v_after.geometry_wkt,
          geometry_source = case
            when v_patch ? 'geometry_wkt' then 'ACT'
            else v_before.geometry_source
          end
      where field_number = v_before.field_number
      returning * into v_after;

      v_updated := v_updated + 1;
    else
      if v_match_count > 0 then
        raise exception 'ACT insert became an existing KC field before apply: %',
          v_change.field_number_norm;
      end if;

      v_patch := v_change.source_payload
        || jsonb_build_object(
          'field_number', v_change.field_number_norm,
          'is_active', true,
          'geometry_source', case
            when v_change.source_payload ? 'geometry_wkt' then 'ACT'
            else null
          end
        );

      select *
      into v_after
      from jsonb_populate_record(null::public.master_fields, v_patch);

      insert into public.master_fields (
        field_number,
        farmer_name,
        grower,
        hybrid,
        total_area_planted_ha,
        discard_area_ha,
        effective_area_ha,
        planting_date_pdn,
        hamlet_dusun,
        village_desa,
        sub_district_kec,
        district_kab,
        fa,
        field_spv,
        coordinate,
        region,
        area_manager,
        type,
        prov,
        planting_ratio,
        planting_space,
        geometry_wkt,
        geometry_source,
        is_active
      ) values (
        v_after.field_number,
        v_after.farmer_name,
        v_after.grower,
        v_after.hybrid,
        v_after.total_area_planted_ha,
        v_after.discard_area_ha,
        v_after.effective_area_ha,
        v_after.planting_date_pdn,
        v_after.hamlet_dusun,
        v_after.village_desa,
        v_after.sub_district_kec,
        v_after.district_kab,
        v_after.fa,
        v_after.field_spv,
        v_after.coordinate,
        v_after.region,
        v_after.area_manager,
        v_after.type,
        v_after.prov,
        v_after.planting_ratio,
        v_after.planting_space,
        v_after.geometry_wkt,
        v_after.geometry_source,
        v_after.is_active
      )
      returning * into v_after;

      v_before := null;
      v_inserted := v_inserted + 1;
    end if;

    insert into public.act_master_fields_change_log (
      run_id,
      field_number,
      operation,
      source_type,
      changed_columns,
      before_payload,
      after_payload
    ) values (
      p_run_id,
      v_change.field_number_norm,
      v_change.change_kind,
      v_change.source_type,
      v_change.changed_columns,
      case
        when v_change.change_kind = 'UPDATE'
          then public.act_master_fields_sync_snapshot(v_before)
        else null
      end,
      public.act_master_fields_sync_snapshot(v_after)
    );

    update public.act_sync_changes
    set applied = true,
        applied_at = now(),
        apply_error = null
    where id = v_change.id;
  end loop;

  update public.act_sync_runs
  set status = 'COMPLETED',
      completed_at = now(),
      summary = summary || jsonb_build_object(
        'applied_insert', v_inserted,
        'applied_update', v_updated
      )
  where id = p_run_id;

  return jsonb_build_object(
    'run_id', p_run_id,
    'inserted', v_inserted,
    'updated', v_updated
  );
end;
$$;

revoke all on function public.apply_act_master_fields_sync(uuid)
  from public, anon, authenticated;
grant execute on function public.apply_act_master_fields_sync(uuid)
  to service_role;

comment on table public.act_sync_runs is
  'One auditable ACT-to-KC master_fields reconciliation run.';
comment on table public.act_sync_rows is
  'Immutable normalized ACT rows staged before reconciliation.';
comment on table public.act_sync_changes is
  'Per-field ACT-versus-KC decision. MISSING_SOURCE is informational and is never applied.';
comment on function public.apply_act_master_fields_sync(uuid) is
  'Applies validated INSERT/UPDATE changes atomically while preserving KC-owned columns.';
