create table if not exists public.got_fet_sample_tracking (
  id bigint generated by default as identity primary key,
  lot_id text not null,
  status text not null,
  actor text,
  event_datetime timestamptz not null default now(),
  remarks text,
  created_by_user_id uuid,
  created_at timestamptz not null default now()
);

create table if not exists public.got_fet_got_observation (
  id bigint generated by default as identity primary key,
  lot_id text not null,
  sample_id text,
  hybrid text,
  plot_id text,
  observation_stage text,
  total_observed integer not null default 0,
  off_type_count integer not null default 0,
  selfing_count integer not null default 0,
  male_count integer not null default 0,
  suspicious_count integer not null default 0,
  true_type_count integer not null default 0,
  purity_percent numeric(8, 2) not null default 0,
  remarks text,
  submitted_by text,
  submitted_datetime timestamptz not null default now(),
  review_status text not null default 'Submitted',
  created_by_user_id uuid,
  created_at timestamptz not null default now()
);

create table if not exists public.got_fet_fet_observation (
  id bigint generated by default as identity primary key,
  lot_id text not null,
  sample_id text,
  hybrid text,
  plot_id text,
  replication integer not null,
  dap integer,
  total_points integer not null default 50,
  grown_count integer not null default 0,
  not_grown_count integer not null default 0,
  review_count integer not null default 0,
  not_readable_count integer not null default 0,
  emergence_percent numeric(8, 2) not null default 0,
  point_statuses jsonb not null default '[]'::jsonb,
  plot_photo_url text,
  remarks text,
  submitted_by text,
  submitted_datetime timestamptz not null default now(),
  review_status text not null default 'Submitted',
  created_by_user_id uuid,
  created_at timestamptz not null default now()
);

create table if not exists public.got_fet_photo_evidence (
  id bigint generated by default as identity primary key,
  lot_id text not null,
  sample_id text,
  test_type text,
  module text not null,
  plot_id text,
  replication text,
  photo_url text not null,
  uploaded_by text,
  uploaded_datetime timestamptz not null default now(),
  review_status text not null default 'Submitted',
  created_by_user_id uuid,
  created_at timestamptz not null default now()
);

create table if not exists public.got_fet_review_history (
  id bigint generated by default as identity primary key,
  lot_id text not null,
  sample_id text,
  module text not null,
  previous_status text,
  new_status text not null,
  review_action text not null,
  reviewer text,
  review_datetime timestamptz not null default now(),
  remarks text,
  created_by_user_id uuid,
  created_at timestamptz not null default now()
);

create table if not exists public.got_fet_final_decision (
  id bigint generated by default as identity primary key,
  lot_id text not null,
  sample_id text,
  module text not null,
  decision text not null,
  decided_by text,
  decision_datetime timestamptz not null default now(),
  remarks text,
  created_by_user_id uuid,
  created_at timestamptz not null default now()
);

create index if not exists got_fet_sample_tracking_lot_idx
  on public.got_fet_sample_tracking (lot_id, event_datetime desc);

create index if not exists got_fet_got_observation_lot_idx
  on public.got_fet_got_observation (lot_id, submitted_datetime desc);

create index if not exists got_fet_fet_observation_lot_idx
  on public.got_fet_fet_observation (lot_id, replication, submitted_datetime desc);

create index if not exists got_fet_photo_evidence_lot_idx
  on public.got_fet_photo_evidence (lot_id, module);

create index if not exists got_fet_review_history_lot_idx
  on public.got_fet_review_history (lot_id, module, review_datetime desc);

create index if not exists got_fet_final_decision_lot_idx
  on public.got_fet_final_decision (lot_id, module, decision_datetime desc);

insert into storage.buckets (id, name, public)
values ('got_fet_evidence', 'got_fet_evidence', true)
on conflict (id) do update
set public = excluded.public;
